//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasylStatementLibrary {
    
    
    #region Component Designer generated code 
    public partial class StatementGenerator_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::FasylStatementLibrary.@__StatementGenerator.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::FasylStatementLibrary.StatementGenerator), typeof(global::FasylStatementLibrary.StatementGenerator_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::FasylStatementLibrary.StatementGenerator), typeof(global::FasylStatementLibrary.StatementGenerator_))]
    internal sealed partial class @__StatementGenerator : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__StatementGenerator(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::FasylStatementLibrary.@__StatementGenerator.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__StatementGenerator);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GenerateStatement", "GenerateStatement0", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lfasylstatementlibrary/mod" +
                        "els/TransactionStatistics;Lfasylstatementlibrary/models/SttbScheduledStatements;" +
                        ")Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GenerateStatmentTest", "GenerateStatmentTest1", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorStatementGenerator0", "__ctorStatementGenerator0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GenerateStatement0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle custId, global::net.sf.jni4net.utils.JniLocalHandle CustomerInfo, global::net.sf.jni4net.utils.JniLocalHandle Transactions, global::net.sf.jni4net.utils.JniLocalHandle statistics, global::net.sf.jni4net.utils.JniLocalHandle statement) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lfasylstatementlibrary/models/TransactionStatistics;Lfasylstatementlibrary/models/SttbScheduledStatements;)Ljava/lang/String;
            // (LSystem/String;LSystem/String;LSystem/String;LFasylStatementLibrary/Models/TransactionStatistics;LFasylStatementLibrary/Models/SttbScheduledStatements;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::FasylStatementLibrary.StatementGenerator @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.StatementGenerator>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GenerateStatement(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, custId), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, CustomerInfo), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, Transactions), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionStatistics>(@__env, statistics), global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.SttbScheduledStatements>(@__env, statement)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GenerateStatmentTest1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle name) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::FasylStatementLibrary.StatementGenerator @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.StatementGenerator>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GenerateStatmentTest(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, name)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void @__ctorStatementGenerator0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.StatementGenerator @__real = new global::FasylStatementLibrary.StatementGenerator();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::FasylStatementLibrary.@__StatementGenerator(@__env);
            }
        }
    }
    #endregion
}
