// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class CustomerInformation extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected CustomerInformation(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public CustomerInformation() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.CustomerInformation.__ctorCustomerInformation0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorCustomerInformation0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getPosition();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setPosition(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCustomerName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCustomerName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCcy();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCcy(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDescription();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setDescription(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAcyOpeningBal();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAcyOpeningBal(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAcyAvlbal();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAcyAvlbal(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCustAcNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCustAcNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCustNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCustNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getBranchCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setBranchCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getBranchName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setBranchName(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getBranchAddr1();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setBranchAddr1(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAddress2();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAddress2(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAcyTodayToverDr();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAcyTodayToverDr(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAcyTodayToverCr();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAcyTodayToverCr(double value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.CustomerInformation.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.CustomerInformation.staticType = staticType;
    }
    //</generated-proxy>
}
