// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class CustomerInformations extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected CustomerInformations(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public CustomerInformations() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.CustomerInformations.__ctorCustomerInformations0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorCustomerInformations0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Collections/Generic/IList`1;")
    public native system.collections.IList getcustomerInformations();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Collections/Generic/IList`1;)V")
    public native void setcustomerInformations(system.collections.IList value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.CustomerInformations.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.CustomerInformations.staticType = staticType;
    }
    //</generated-proxy>
}
