// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class SttbScheduledStatements extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SttbScheduledStatements(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public SttbScheduledStatements() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.SttbScheduledStatements.__ctorSttbScheduledStatements0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorSttbScheduledStatements0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getguid();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setguid(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getcustNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setcustNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getacNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setacNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Nullable`1;")
    public native system.ValueType getstartDate();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Nullable`1;)V")
    public native void setstartDate(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Nullable`1;")
    public native system.ValueType getendDate();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Nullable`1;)V")
    public native void setendDate(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getstmntType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setstmntType(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getstatus();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setstatus(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Nullable`1;")
    public native system.ValueType getscheduleStamp();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Nullable`1;)V")
    public native void setscheduleStamp(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getemail();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setemail(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getstmtPass();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setstmtPass(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Nullable`1;")
    public native system.ValueType getstmtDtSend();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Nullable`1;)V")
    public native void setstmtDtSend(system.ValueType value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getpdfPath();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setpdfPath(java.lang.String value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.SttbScheduledStatements.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.SttbScheduledStatements.staticType = staticType;
    }
    //</generated-proxy>
}
