// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class StvwTransaction extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected StvwTransaction(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public StvwTransaction() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.StvwTransaction.__ctorStvwTransaction0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorStvwTransaction0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getTrnRefNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setTrnRefNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAcEntrySrNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAcEntrySrNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAcNo();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAcNo(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAcCcy();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAcCcy(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDrCrInd();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setDrCrInd(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getNarration();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setNarration(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getFcyAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setFcyAmount(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getLcyAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setLcyAmount(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getTrnDt();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/DateTime;)V")
    public native void setTrnDt(system.DateTime value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getValueDt();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/DateTime;)V")
    public native void setValueDt(system.DateTime value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getInstrumentCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setInstrumentCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getAcDesc();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setAcDesc(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDescription();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setDescription(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAcyOpeningBal();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAcyOpeningBal(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getDebit();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setDebit(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getCredit();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setCredit(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getRunningBal();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setRunningBal(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAmount();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAmount(double value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.StvwTransaction.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.StvwTransaction.staticType = staticType;
    }
    //</generated-proxy>
}
