// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class TransactionHistory extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected TransactionHistory(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public TransactionHistory() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.TransactionHistory.__ctorTransactionHistory0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorTransactionHistory0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LFasylStatementLibrary/Models/AllCustomerAccount;")
    public native fasylstatementlibrary.models.AllCustomerAccount getAllCustomerAccount();
    
    @net.sf.jni4net.attributes.ClrMethod("(LFasylStatementLibrary/Models/AllCustomerAccount;)V")
    public native void setAllCustomerAccount(fasylstatementlibrary.models.AllCustomerAccount value);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Collections/Generic/List`1;")
    public native system.Object getStvwTransactions();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Collections/Generic/List`1;)V")
    public native void setStvwTransactions(system.Object value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.TransactionHistory.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.TransactionHistory.staticType = staticType;
    }
    //</generated-proxy>
}
