// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class TransactionHistories extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected TransactionHistories(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public TransactionHistories() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.TransactionHistories.__ctorTransactionHistories0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorTransactionHistories0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Collections/Generic/List`1;")
    public native system.Object gettransactionHistories();
    
    @net.sf.jni4net.attributes.ClrMethod("([[LSystem/Collections/Generic/List`1;)V")
    public native void settransactionHistories(system.Object value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.TransactionHistories.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.TransactionHistories.staticType = staticType;
    }
    //</generated-proxy>
}
