// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package fasylstatementlibrary.models;

@net.sf.jni4net.attributes.ClrType
public class TransactionStatistics extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected TransactionStatistics(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public TransactionStatistics() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        fasylstatementlibrary.models.TransactionStatistics.__ctorTransactionStatistics0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorTransactionStatistics0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTotalNumOfTransaction();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTotalNumOfTransaction(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalCredits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalCredits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalDebits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalDebits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTotalAtmTransaction();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTotalAtmTransaction(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalAtmCredits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalAtmCredits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalAtmDebits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalAtmDebits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalAtmPercent();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalAtmPercent(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getTotalPosTransaction();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setTotalPosTransaction(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalPosCredits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalPosCredits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalPosDebits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalPosDebits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getTotalPosPercent();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setTotalPosPercent(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getOthersTotalTransaction();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setOthersTotalTransaction(int value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getOthersTotalCredits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setOthersTotalCredits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getOthersTotalDebits();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setOthersTotalDebits(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getOthersTotalPercent();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setOthersTotalPercent(double value);
    
    public static system.Type typeof() {
        return fasylstatementlibrary.models.TransactionStatistics.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        fasylstatementlibrary.models.TransactionStatistics.staticType = staticType;
    }
    //</generated-proxy>
}
