//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasylStatementLibrary.Models {
    
    
    #region Component Designer generated code 
    public partial class TransactionHistories_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::FasylStatementLibrary.Models.@__TransactionHistories.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::FasylStatementLibrary.Models.TransactionHistories), typeof(global::FasylStatementLibrary.Models.TransactionHistories_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::FasylStatementLibrary.Models.TransactionHistories), typeof(global::FasylStatementLibrary.Models.TransactionHistories_))]
    internal sealed partial class @__TransactionHistories : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__TransactionHistories(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::FasylStatementLibrary.Models.@__TransactionHistories.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__TransactionHistories);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "gettransactionHistories", "transactionHistories0", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "settransactionHistories", "transactionHistories1", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorTransactionHistories0", "__ctorTransactionHistories0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle transactionHistories0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()[[LSystem/Collections/Generic/List`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::FasylStatementLibrary.Models.TransactionHistories @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistories>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.Generic.List<FasylStatementLibrary.Models.TransactionHistory>>(@__env, @__real.transactionHistories);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void transactionHistories1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // ([[LSystem/Collections/Generic/List`1;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.Models.TransactionHistories @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistories>(@__env, @__obj);
            @__real.transactionHistories = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.Generic.List<FasylStatementLibrary.Models.TransactionHistory>>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorTransactionHistories0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.Models.TransactionHistories @__real = new global::FasylStatementLibrary.Models.TransactionHistories();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::FasylStatementLibrary.Models.@__TransactionHistories(@__env);
            }
        }
    }
    #endregion
}
