//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasylStatementLibrary.Models {
    
    
    #region Component Designer generated code 
    public partial class TransactionHistory_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::FasylStatementLibrary.Models.@__TransactionHistory.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::FasylStatementLibrary.Models.TransactionHistory), typeof(global::FasylStatementLibrary.Models.TransactionHistory_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::FasylStatementLibrary.Models.TransactionHistory), typeof(global::FasylStatementLibrary.Models.TransactionHistory_))]
    internal sealed partial class @__TransactionHistory : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__TransactionHistory(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::FasylStatementLibrary.Models.@__TransactionHistory.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__TransactionHistory);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAllCustomerAccount", "AllCustomerAccount0", "()Lfasylstatementlibrary/models/AllCustomerAccount;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAllCustomerAccount", "AllCustomerAccount1", "(Lfasylstatementlibrary/models/AllCustomerAccount;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStvwTransactions", "StvwTransactions2", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setStvwTransactions", "StvwTransactions3", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorTransactionHistory0", "__ctorTransactionHistory0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle AllCustomerAccount0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lfasylstatementlibrary/models/AllCustomerAccount;
            // ()LFasylStatementLibrary/Models/AllCustomerAccount;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::FasylStatementLibrary.Models.TransactionHistory @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::FasylStatementLibrary.Models.AllCustomerAccount>(@__env, @__real.AllCustomerAccount);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AllCustomerAccount1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lfasylstatementlibrary/models/AllCustomerAccount;)V
            // (LFasylStatementLibrary/Models/AllCustomerAccount;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.Models.TransactionHistory @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistory>(@__env, @__obj);
            @__real.AllCustomerAccount = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.AllCustomerAccount>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle StvwTransactions2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()[[LSystem/Collections/Generic/List`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::FasylStatementLibrary.Models.TransactionHistory @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistory>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.Generic.List<FasylStatementLibrary.Models.StvwTransaction>>(@__env, @__real.StvwTransactions);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void StvwTransactions3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // ([[LSystem/Collections/Generic/List`1;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.Models.TransactionHistory @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::FasylStatementLibrary.Models.TransactionHistory>(@__env, @__obj);
            @__real.StvwTransactions = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.Generic.List<FasylStatementLibrary.Models.StvwTransaction>>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorTransactionHistory0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::FasylStatementLibrary.Models.TransactionHistory @__real = new global::FasylStatementLibrary.Models.TransactionHistory();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::FasylStatementLibrary.Models.@__TransactionHistory(@__env);
            }
        }
    }
    #endregion
}
